import aoc2024.day1.Day1Solution;
import aoc2024.day10.Day10Solution;
import aoc2024.day11.Day11Solution;
import aoc2024.day12.Day12Solution;
import aoc2024.day13.Day13Solution;
import aoc2024.day14.Day14Solution;
import aoc2024.day15.Day15Solution;
import aoc2024.day16.Day16Solution;
import aoc2024.day17.Day17Solution;
import aoc2024.day18.Day18Solution;
import aoc2024.day19.Day19Solution;
import aoc2024.day2.Day2Solution;
import aoc2024.day20.Day20Solution;
import aoc2024.day21.Day21Solution;
import aoc2024.day22.Day22Solution;
import aoc2024.day23.Day23Solution;
import aoc2024.day24.Day24Solution;
import aoc2024.day3.Day3Solution;
import aoc2024.day4.Day4Solution;
import aoc2024.day5.Day5Solution;
import aoc2024.day6.Day6Solution;
import aoc2024.day7.Day7Solution;
import aoc2024.day8.Day8Solution;
import aoc2024.day9.Day9Solution;

public class App {
    public static void main(String[] args) throws Exception {
        System.out.println("--------------------------DAY 1--------------------------");
        Day1Solution.day1Solution();
        System.out.println("--------------------------DAY 2--------------------------");
        Day2Solution.day2Solution();
        System.out.println("--------------------------DAY 3--------------------------");
        Day3Solution.day3Solution();
        System.out.println("--------------------------DAY 4--------------------------");
        Day4Solution.day4Solution();
        System.out.println("--------------------------DAY 5--------------------------");
        Day5Solution.day5Solution();
        System.out.println("--------------------------DAY 6--------------------------");
        Day6Solution.day6Solution();
        System.out.println("--------------------------DAY 7--------------------------");
        Day7Solution.day7Solution();
        System.out.println("--------------------------DAY 8--------------------------");
        Day8Solution.day8Solution();
        System.out.println("--------------------------DAY 9--------------------------");
        Day9Solution.day9Solution();
        System.out.println("--------------------------DAY10--------------------------");
        Day10Solution.day10Solution();
        System.out.println("--------------------------DAY11--------------------------");
        Day11Solution.day11Solution();
        System.out.println("--------------------------DAY12--------------------------");
        Day12Solution.day12Solution();
        System.out.println("--------------------------DAY13--------------------------");
        Day13Solution.day13Solution();
        System.out.println("--------------------------DAY14--------------------------");
        Day14Solution.day14Solution();
        System.out.println("--------------------------DAY15--------------------------");
        Day15Solution.day15Solution();
        System.out.println("--------------------------DAY16--------------------------");
        Day16Solution.day16Solution();
        System.out.println("--------------------------DAY17--------------------------");
        Day17Solution.day17Solution();
        System.out.println("--------------------------DAY18--------------------------");
        Day18Solution.day18Solution();
        System.out.println("--------------------------DAY19--------------------------");
        Day19Solution.day19Solution();
        System.out.println("--------------------------DAY20--------------------------");
        Day20Solution.day20Solution();
        System.out.println("--------------------------DAY21--------------------------");
        Day21Solution.day21Solution();
        System.out.println("--------------------------DAY22--------------------------");
        Day22Solution.day22Solution();
        System.out.println("--------------------------DAY23--------------------------");
        Day23Solution.day23Solution();
        System.out.println("--------------------------DAY24--------------------------");
        Day24Solution.getDay24Solution();
    }
}